---
version: "3"
services:
  cachyos_discord_bot:
    container_name: cachyos_discord_bot
    hostname: cachyos_discord_bot
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    env_file: '.env'
    restart: always
